version: '2'

services:
    web:
        image: nginx:latest
        labels:
            - "traefik.enable=true"
            - "traefik.backend=todo_web"
            - "traefik.frontend.rule=Host:${WEB_DOMAIN}"
            - "traefik.docker.network=web"
            - "traefik.port=${NGINX_PORT}"
        volumes:
            - .:/usr/share/nginx/html:ro
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - web
            - internal
    php:
        build:
            context: ./docker/php-fpm
        image: shaifulphp
        labels:
            - "traefik.enable=false"
        volumes:
            - .:/usr/share/nginx/html:ro
            - ./docker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - internal
    composer:
        image: composer/composer:php7
        command: install --ignore-platform-reqs
        labels:
            - "traefik.enable=false"
        volumes:
            - .:/app
        networks:
            - internal
    db:
        image: mariadb:latest
        labels:
            - "traefik.enable=false"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        #     - ./database:/var/lib/mysql
        networks:
            - internal
    adminer:
        image: adminer
        labels:
            - "traefik.enable=true"
            - "traefik.backend=todo_adminer"
            - "traefik.frontend.rule=Host:adminer.todo.local"
            - "traefik.docker.network=web"
            - "traefik.port=8080"
        networks:
            - internal
            - web

networks:
    web:
        external: true
    internal:
        external: false
