version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/usr/share/nginx/html:ro
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: ./docker/php-fpm
        image: shaifulphp
        volumes:
            - .:/usr/share/nginx/html:ro
            - ./docker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    composer:
        image: composer/composer:php7
        command: install --ignore-platform-reqs
        volumes:
            - .:/app
    db:
        image: mariadb:latest
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root123
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        #     - ./database:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - 8081:8080
