version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/usr/share/nginx/html:ro
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: ./php-fpm
        volumes:
            - .:/usr/share/nginx/html:ro
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        #     - ./database:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - 8080:8080